<style type="text/css">
/* Syntax-Markierung */

pre {
    /*background-color: #FDF6E3;*/
    font-family: "LettrGoth12 BT", monospace;
    font-size: 1.0em;
    line-height: 1.1em;
}

.sourceCode {
    font-family: "LettrGoth12 BT", monospace;
    font-size: 1.0em;
    line-height: 1.1em;
}

@media print {
   pre {
       font-size: 9pt;
       line-height: 12pt;
   }

   .sourceCode {
       font-size: 9pt;
       line-height: 12pt;
   }

   tr.sourceCode {
      border: 1px solid lightgray;
   }

}

.sourceCode tr:nth-of-type(odd) {
   background-color: transparent;
}

/* KeyWordTok */
.sourceCode .kw { color: #268BD2; }
/* DataTypeTok */
.sourceCode .dt { color: #268BD2; }

/* DecValTok (decimal value), BaseNTok, FloatTok
.sourceCode .dv, .sourceCode .bn, .sourceCode .fl { color: #D33682; }
/* CharTok */
.sourceCode .ch { color: #DC322F; }
/* StringTok */
.sourceCode .st { color: #2AA198; }
/* CommentTok */
.sourceCode .co { color: #93A1A1; }
/* OtherTok */
.sourceCode .ot { color: #A57800; }
/* AlertTok */
.sourceCode .al { color: #CB4B16; font-weight: bold; }
/* FunctionTok */
.sourceCode .fu { color: #268BD2; }
/* RegionMarkerTok */
.sourceCode .re { }

/* EOF */
</style>
